project/config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'carts/:id' => "carts#index", as: "cart"
  get 'welcome/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  post 'line_items/:id/add' => "line_items#add_quantity", as: "line_item_add"
  post 'line_items/:id/reduce' => "line_items#reduce_quantity", as: "line_item_reduce"
  post 'line_items' => "line_items#create"
  get 'line_items/:id' => "line_items#show", as: "line_item"
  delete 'line_items/:id' => "line_items#destroy"
  
  resources :carts
  resources :snacks
end

project/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

project/app/models/cart.rb
class Cart < ApplicationRecord
    has_many :line_items, dependent: :destroy
    has_many :snacks, through: :line_items 

    def total
        sum = 0
        self.line_items.each do |line_item|
          sum+= line_item.quantity * line_item.snack.price
        end
        return sum
    end
end

project/app/models/line_item.rb
class LineItem < ApplicationRecord
    belongs_to :snack
    belongs_to :cart
end

project/app/models/snack.rb
class Snack < ApplicationRecord
    validates :name, presence: true, length: { minimum: 3 }
    has_many :line_items, dependent: :destroy
end

project/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :current_cart

  # def cart 
  #   @cart = Cart.create
  # end 

  private
    def current_cart
      if session[:cart_id]
        cart = Cart.find_by(:id => session[:cart_id])
        if cart.present?
          @current_cart = cart
        else
          session[:cart_id] = nil
        end
      end

      if session[:cart_id] == nil
        @current_cart = Cart.create
        session[:cart_id] = @current_cart.id
    end
  end

end

project/app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def index
    @cart = @current_cart
  end

  def destroy
    @cart = @current_cart
    @cart.destroy
    session[:cart_id] = nil
    redirect_to root_path
  end

end

project/app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController

    def create
        
        chosen_snack = Snack.find(params[:snack_id])
        current_cart = @current_cart

        if current_cart.snacks.include?(chosen_snack)
            @line_item = current_cart.line_items.find_by(:snack_id => chosen_snack)
            @line_item.quantity += 1
        else
            @line_item = LineItem.new
            @line_item.cart = current_cart
            @line_item.snack = chosen_snack
        end

        @line_item.save
        redirect_to cart_path(current_cart)
    end

    def add_quantity
        @line_item = LineItem.find(params[:id])
        @line_item.quantity += 1
        @line_item.save
        redirect_to cart_path(@current_cart)
    end
      
    def reduce_quantity
        @line_item = LineItem.find(params[:id])
        if @line_item.quantity > 1
          @line_item.quantity -= 1
        end
        @line_item.save
        #puts "Line Item: #{@line_item.snack_id} Quantity: #{@line_item.quantity}"
        redirect_to cart_path(@current_cart)
    end

    def destroy
        @line_item = LineItem.find(params[:id])
        @line_item.destroy
        redirect_to cart_path(@current_cart)
    end 

end

private
    def line_item_params
        params.require(:line_item).permit(:quantity,:snack_id, :cart_id)
    end

project/app/controllers/snacks_controller.rb
class SnacksController < ApplicationController
    def index 
        @snack = Snack.all
    end 
    
    def show 
        @snack = Snack.find(params[:id])
    end 

    # def create 
    #     @snack = Snack.new(snack_params)

    #     if @snack.save
    #         redirect_to @snack 
    #     else
    #         render 'new'
    #     end
    # end 

    # def update 
    #     @snack = Snack.find(params[:id])

    #     if @snack.update(snack_params)
    #         redirect_to @snack
    #     else
    #         render 'edit'
    #     end
    # end

    # def destroy 
    #     @snack = Snack.find(params[:id])
    #     @snack.destroy

    #     redirect_to snacks_path
    # end 

    private
        def snack_params
            params.require(:snack).permit(:name, :price)
        end
end

project/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index 
  end 

  # def index 
  #   @welcome = Welcome.all
  # end 

  # def show 
  #   @welcome = Welcome.find(params[:id])
  # end 

  # def create 
  #   @welcome = Welcome.new(welcome_params)

  #   if @welcome.save
  #       redirect_to @welcome 
  #   else
  #       render 'new'
  #   end
  # end 

  # def update 
  #   @welcome = Welcome.find(params[:id])

  #   if @welcome.update(welcome_params)
  #       redirect_to @welcome
  #   else
  #       render 'edit'
  #   end
  # end

  # def destroy 
  #   @welcome = Welcome.find(params[:id])
  #   @welcome.destroy

  #   redirect_to welcomes_path
  # end 
end

project/app/helpers/application_helper.rb
module ApplicationHelper
end

project/app/helpers/carts_helper.rb
module CartsHelper
end

project/app/helpers/line_items_helper.rb
module LineItemsHelper
end

project/app/helpers/snacks_helper.rb
module SnacksHelper
end

project/app/helpers/welcome_helper.rb
module WelcomeHelper
end

project/app/views/carts/index.html.erb
<div id="nav-bar">
  <h1>Cart</h1>
  <div id="nav-links">
    <p id="links"><%= link_to 'Home', controller: 'welcome' %></p>
    <p id="links"><%= link_to 'Snacks', controller: 'snacks' %></p>
    <p id="links"><%= link_to 'Cart', controller: 'carts' %></p>
  </div>
</div>
<%= link_to 'Back', snacks_path %>

<div id="carts-container">
 
  <% @cart.line_items.each do |line_item| %>
    <div id="cart-container">
        <h4 id="cart-item">Item: <%= line_item.snack.name %><br/>Price of Items: <%= number_to_currency(line_item.snack.price * line_item.quantity, :unit => "$")%></h4>
        <div id="cart-buttons">
          <%= button_to "+", line_item_add_path(:id => line_item), method: :post%>
          <%=line_item.quantity%>
          <%= button_to "-", line_item_reduce_path(:id => line_item), method: :post %>
          <div id="cart-delete">
          <%= button_to "remove", line_item_path(line_item), method: :delete %>
          </div>
        </div>
    </div>
  <% end %>
  Total: <%= number_to_currency(@cart.total, :unit => "$")%>

  <%= link_to "Empty cart", cart_path(@current_cart),method: :delete %>

</div>

project/app/views/carts/show.html.erb
<h1>Carts Show</h1>

<div id="carts-container">
 
  <% @cart.line_items.each do |line_item| %>
    <div id="cart-container">
        <h4>Item: <%= line_item.snack.name %></h4>
    </div>
  <% end %>

</div>

project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

project/app/views/snacks/_form.html.erb
<%= form_with model: @snack, local: true do |form| %>
 
    <% if @snack.errors.any? %>
        <div id="error_explanation">
        <h2>
            <%= pluralize(@snack.errors.count, "error") %> 
            prohibited this snack from being saved:
        </h2>
        <ul>
            <% @snack.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
        </ul>
        </div>
    <% end %>
    
    <p>
        <%= form.label :name %><br>
        <%= form.text_field :name %>
    </p>
    
    <p>
        <%= form.label :price %><br>
        <%= form.text_field :price %>
    </p>
    
    <p>
        <%= form.submit %>
    </p>
    
<% end %>

project/app/views/snacks/index.html.erb
<div id="nav-bar">
  <h1>Quarantine Snacks</h1>
  <div id="nav-links">
    <p id="links"><%= link_to 'Home', controller: 'welcome' %></p>
    <p id="links"><%= link_to 'Snacks', controller: 'snacks' %></p>
    <p id="links"><%= link_to 'Cart', controller: 'carts' %></p>
  </div>
</div>

<div id="snacks-container">
 
  <% @snack.each do |snack| %>
    <div id="snack-container">
      <div id="home-snack">
        
        <% Dir.glob('app/assets/images/*').map do |path| %>
          <%# <p><%= path.split("/")[-1].split(".")[0] %%>
          <% if snack.name === path.split("/")[-1].split(".")[0] %>
            <div id="snack-img"><%= image_tag("#{ File.basename(path) }", :size => "70x70") %></div>
          
          <% end %>
        <% end %>
      
        <h4><%= snack.name %></h4>
        <p><%= number_to_currency(snack.price, :unit => "$") %></p>
      </div>
      <div id="snack-buttons">
        <%= button_to "Add to Cart", line_items_path(:snack_id => snack.id) %>
      </div>
    </div>
  <% end %>

</div>

 

project/app/views/snacks/show.html.erb
<p>
  <strong>Snack:</strong>
  <%= @snack.name %>
</p>
 
<p>
  <strong>Price:</strong>
  <%= @snack.price %>
</p>

<%= link_to 'Back', snacks_path %>

project/app/views/welcome/index.html.erb
<div id="nav-bar">
  <h1>Quarantine Snacks</h1>
  <div id="nav-links">
    <p id="links"><%= link_to 'Home', controller: 'welcome' %></p>
    <p id="links"><%= link_to 'Snacks', controller: 'snacks' %></p>
    <p id="links"><%= link_to 'Cart', controller: 'carts' %></p>
  </div>
</div>
<p>Stay Healthy and Hungry!</p>

<p><%= image_tag "chips.jpg"%></p>


<%# <%= form_with scope: :welcome, local: true do |form| 
  <p>
    <%= form.label :name ><br>
    <%= form.text_field :name >
  </p>
 
  <p>
    <%= form.label :comment ><br>
    <%= form.text_area :comment >
  </p>
 
  <p>
    <%= form.submit >
  </p>
%>